### DISCUSSION TITLE
Mongoose Populate

### DISCUSSION THREAD

**Discussion by lxhan** [typegoose/mongodb-memory-server#518] [Q&A]
## Versions

- NodeJS: 15.2.1
- mongodb-memory-server-*: 7.3.4
- mongodb: 5.0.1
- mongoose: 5.7.13 
- system:  MacOS

package: mongo-memory-server

## What is your question?

Is mongoose population supported? 

Models

```ts
const MerchantSchema = Schema({
  restaurants: [{ type: Schema.Types.ObjectId, ref: 'restaurant' }]
});

const RestaurantSchema = Schema({
  owner: Schema.Types.ObjectId,
});

RestaurantSchema.virtual('merchant', {
  ref: 'merchant',
  localField: 'owner',
  foreignField: '_id',
  justOne: true,
})
```

This code is working with real mongodb and in docker but I can't get it working with jest and mongodb-memory-server.
I tried with normal population and with virtuals but I get empty object where I should get populated. 

```ts
await Restaurant.findById(id).populate('merchant');
```

**Comment by hasezoey** [comment]
> Is mongoose population supported?

Why shouldn't it be supported? when you refer to `real mongodb` as in `manually starting and using an binary`, then it should not be different, as long as nothing Atlas exclusive (which populate is not), then everything should work the same

> but I can't get it working with jest and mongodb-memory-server.

because of the reason mentioned above, it should work the same, only difference by default is that this library here use the storage engine `ephemeralForTest`, which does not persist data across restarts

---

to help further, please provide a full jest file (or full reproduction repository if multiple files) to help with this

**Reply by lxhan** [reply]
fake db 

```ts
import mongoose from 'mongoose';
import { MongoMemoryServer } from 'mongodb-memory-server';

let mongod: MongoMemoryServer;

export const connect = async () => {
  mongod = await MongoMemoryServer.create({
    binary: {
      version: '5.0.1',
    },
  });
  const uri = mongod.getUri();

  const mongooseOptions = {
    useNewUrlParser: true,
    useUnifiedTopology: true,
    useCreateIndex: true,
  };

  await mongoose.connect(uri, mongooseOptions);
};

export const disconnect = async () => {
  await mongoose.connection.close();
  await mongod.stop();
};
```


test file

```ts
beforeAll(() => connect());

afterAll(() => disconnect());

describe('placeOrder', () => {
  it('should create product and populate modifiers', async () => {
    // in generateMockDataForPlaceOrder I'm creating product with 2 modifiers
    await generateMockDataForPlaceOrder();

    // here when populating I'll get product with modifier populated 
    const product = await Product.findById(id).populate({ path: 'modifier' });

    // product.modifier
    {
        id: 1623306319264,
        name: 'mod 2',
        sortOrder: 0,
        isFixed: false,
        numOfModifiers: 3
    }

    expect(product.modifier.name).toEqual('mod 2');
  });
});
```

**Reply by hasezoey** [reply]
i forgot to mentioned, mongoose currently (version 5.13) does not support mongodb `5.x`, because officially you would require either mongodb(driver) `3.7` or `4.x`, and mongoose currently (5.13) uses mongodb `3.6`

thanks for the code, after looking at it, i dont see anything wrong (aside from the version mentioned above)
could you list what you mean with `real mongodb` and `docker` (as in, which distro, binary version, and way you start it)?

**Reply by lxhan** [reply]
Initially I used default version `4.x`.
By real mongodb I mean atlas.
Docker v 20.10.7  

docker-compose.yml
```
version: "3"

services:
  db:
    user: $UID
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
      MONGO_USERNAME: ${DB_USER}
      MONGO_PASSWORD: ${DB_PASS}
    volumes:
      - ./data:/data/db
      - ./db-init.sh:/docker-entrypoint-initdb.d/db-init.sh:ro
```

db-init.sh
```
mongo -- "$MONGO_INITDB_DATABASE" <<EOF
  db.createUser({
    user: "$MONGO_USERNAME",
    pwd: "$MONGO_PASSWORD",
    roles: [
      { role: 'readWrite', db: "$MONGO_INITDB_DATABASE" }
    ]
  });
EOF
```
