### DISCUSSION TITLE
setup on GitHub actions

### DISCUSSION THREAD

**Discussion by waigel** [typegoose/mongodb-memory-server#566] [Q&A] [answered]
Hello,
we would automate our tests built on the mongodb-memory-server with GitHub actions. Unfortunately we get an undefined response back for each database request and later a timeout.  
So the question, is it possible to integrate the server into a GitHub action workflow and if so what configuration needs to be done for that.
Thank you 😄

**Comment by hasezoey** [comment, marked as answer]
it is possible, because this package uses github actions to test itself, and a (production ready) example can be seen with the project [typegoose](https://github.com/typegoose/typegoose/) which uses this package

most relevant parts from typegoose's example:
- [workflow file](https://github.com/typegoose/typegoose/blob/master/.github/workflows/tests.yml)
- [jest config](https://github.com/typegoose/typegoose/blob/master/jest.config.json)
- [global setup](https://github.com/typegoose/typegoose/blob/master/test/globalSetup.ts)
- [global teardown](https://github.com/typegoose/typegoose/blob/master/test/globalTeardown.ts)
- [setup file](https://github.com/typegoose/typegoose/blob/master/test/setupFile.ts)
- [mongoose connect util](https://github.com/typegoose/typegoose/blob/master/test/utils/connect.ts)

see also:
- [Integration Examples: Test Runners](https://nodkz.github.io/mongodb-memory-server/docs/guides/integration-examples/test-runners)
- [Integration Examples: Docker](https://nodkz.github.io/mongodb-memory-server/docs/guides/integration-examples/docker)

PS: i will convert this issue to a discussion

---

> Unfortunately we get an undefined response back for each database request and later a timeout.

if it still happens after looking at the examples and changing what is "obvious", please provide a reproduction repository (or the actual repository where it happens, if possible) and / or the error

**Comment by Pyakz** [comment]
```yml
name: End to End Tests

on:
  push:
    branches:
      - '*' # run to all branches

jobs:
  e2e-check:
    name: Testing Endpoints
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup yarn
        run: npm install -g yarn

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Run Audit
        run: (yarn audit || exit 0)

      - name: Run end to end tests
        run: yarn test:e2e
```






Hi, how do i structure my ymal file for this to work?
