### DISCUSSION TITLE
Gitlab Pipeline Jest Failures + Timeouts

### DISCUSSION THREAD

**Discussion by scottenock** [typegoose/mongodb-memory-server#684] [Show and tell]
Creating an issue here for visibility. 

This package by default download mongo in the home directory (`~/.cache/mongodb-binaries`).

As a result Gitlab CI in the next stages of your pipeline won't have it installed and it'll hang when trying to run your tests. 

You can specify a different location for this package (`MONGOMS_DOWNLOAD_DIR`) to download the binary to, cache it, and then use it in the next steps of your pipeline.

Example Pipeline:

```
image: node:lts

stages:
  - install
  - test
  - build

cache: &global_cache
  key:
    files:
      - yarn.lock
  paths:
    - .yarn-cache
    - node_modules
    - mongobinary
  policy: pull

install-packages:
  stage: install
  variables: 
    MONGOMS_DOWNLOAD_DIR: "$CI_PROJECT_DIR/mongobinary"
  cache:
    <<: *global_cache
    policy: pull-push
  script:
    - echo 'yarn-offline-mirror ".yarn-cache/"' >> .yarnrc
    - echo 'yarn-offline-mirror-pruning true' >> .yarnrc
    - yarn install --frozen-lockfile --no-progress

run-tests:
  stage: test
  variables:
    MONGOMS_DOWNLOAD_DIR: "$CI_PROJECT_DIR/mongobinary"
  script:
    - yarn test

build-app:
  stage: build
  variables:
    NODE_ENV: production
  script:
    - yarn build

```
