### DISCUSSION TITLE
Is the package not using cache properly in our ci runs ?

### DISCUSSION THREAD

**Discussion by AnthonyLenglet** [typegoose/mongodb-memory-server#688] [Q&A] [answered]
Hi !

I've been noticing that our ci has been really slow due to a mongodb download happening despite it being seemingly found in the cache folder

```
Mongodb-Memory-Server* checking MongoDB binaries
Downloading MongoDB "4.4.9": 0% (0mb / 68.7mb)
Downloading MongoDB "4.4.9": 100% (68.7mb / 68.7mb)
Mongodb-Memory-Server* found binary: "/home/runner/.cache/mongodb-binaries/mongod-x64-ubuntu-4.4.9"
```

```
PASS src/projects/tests/projects.service.spec.ts (36.746 s)
  ● Console

    console.log
      Downloading MongoDB 4.4.9: 0 % (0mb / 68.6mb)

      at MongoBinaryDownload.Object.<anonymous>.MongoBinaryDownload.printDownloadProgress (node_modules/mongodb-memory-server-core/src/util/MongoBinaryDownload.ts:424:15)

    console.log
      Downloading MongoDB 4.4.9: 40.7 % (27.9mb / 68.6mb)

      at MongoBinaryDownload.Object.<anonymous>.MongoBinaryDownload.printDownloadProgress (node_modules/mongodb-memory-server-core/src/util/MongoBinaryDownload.ts:424:15)

    console.log
      Downloading MongoDB 4.4.9: 82.3 % ([56](https://github.com/Passiverecords/Oney-API/runs/7977031901?check_suite_focus=true#step:5:57).5mb / [68](https://github.com/Passiverecords/Oney-API/runs/7977031901?check_suite_focus=true#step:5:69).6mb)

      at MongoBinaryDownload.Object.<anonymous>.MongoBinaryDownload.printDownloadProgress (node_modules/mongodb-memory-server-core/src/util/MongoBinaryDownload.ts:424:15)
```

our `jest-mongodb-config.ts` file currently looks like this
```
export default {
  mongodbMemoryServerOptions: {
    binary: {
      version: '4.4.9',
      skipMD5: true,
    },
    autoStart: false,
    instance: {},
  },
};
```

is somethign wrong with the way it is currently set up ?

**Comment by hasezoey** [comment]
weird that it does not use the downloaded binary but needs to re-download it in the tests
could you provide:
- what ci are you using (github actions / gitlab runner / travis, etc)
- where are you applying `mongodbMemoryServerOptions` to? (because this is not read normally by MMS itself)

> I've been noticing that our ci has been really slow due to a mongodb download happening despite it being seemingly found in the cache folder

from what i know, most ci runners dont cache `~/.cache` by default, and would need to be done by the user (though in MMS's case i would recommend to explicitly set the [`DOWNLOAD_DIR`](https://nodkz.github.io/mongodb-memory-server/docs/api/config-options#download_dir) config option and cache that)

**Comment by AnthonyLenglet** [comment]
We're using github actions to run the ci with the following steps:
```yaml
steps:
      - name: Load repository
        uses: actions/checkout@master
        with:
          persist-credentials: false
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 12
          cache: 'npm'
        env:
          REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
      - name: Run tests
        timeout-minutes: 30
        env:
          REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
        run: |
          npm ci
          npm run test:cov
```

As for `mongodbMemoryServerOptions`, this is coming from [@shelf/jest-mongodb](https://www.npmjs.com/package/@shelf/jest-mongodb), a jest preset for this package

> from what i know, most ci runners dont cache ~/.cache by default, and would need to be done by the user (though in MMS's case i would recommend to explicitly set the DOWNLOAD_DIR config option and cache that)

I wonder if something about this changed, since re-running the job for the CI still tells me that the binary was found in `~/.cache`, despite me not having set `DOWNLOAD_DIR`, maybe github action is one of the few that caches it ?
