### ISSUE TITLE
Github actions + npm ci --ignore-scripts = flaky ci/cd testing

### ISSUE THREAD

**Issue by natlibfi-jonollil** [typegoose/mongodb-memory-server#925]
## Versions

- NodeJS: 20.x.x (Most likely earlier too)
- mongodb-memory-server-*: 10.1.4
- mongodb(the binary version): ?
- mongodb(the js package): 6.14.2
- system: docker.io/node:20-bookworm

package: mongo-memory-server 

## What is the Problem?

On github actions, if app is installed using `npm ci --ignore-scripts`. It can make CI/CD testing flaky.

## Code Example

```yaml
name: Node-tests
 
on: push
 
jobs:
  test-node-20:
    name: Node 20
    runs-on: ubuntu-latest
 
    container:
      image: docker.io/node:20-bookworm

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - run: npm audit --package-lock-only --audit-level=high
      - run: npm ci --ignore-scripts
      - run: npm test
```
`npm test` script just has some basic mocha chai unit test.

```txt
Run npm test

> @my/package@1.0.0-alpha.1 test
> DOTENV_CONFIG_PATH=.env.test mocha -r dotenv/config --config mocha.config.json src/**/*.spec.mjs

  app
Error: Process completed with exit code 2.
```

We think that it is related to `"postinstall": "husky install",` script that is not allowed to do its job. Why it sometimes work is mystery.
